In [120]:
import numpy as np

In [121]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [122]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [123]:
mean_a = a.mean(axis = 0)

In [124]:
mean_a

array([2. , 8.4])

In [125]:
a_centered = a - mean_a

In [126]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [127]:
x = a_centered[:, :1]

In [128]:
x

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [129]:
y = a_centered[:, 1:2]

In [130]:
y

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [131]:
yt = np.transpose(y)

In [132]:
yt


array([[-2.4, -0.4,  2.6,  1.6, -1.4]])

In [133]:
xt = np.transpose(x)

In [134]:
xt

array([[-1.,  0.,  1.,  1., -1.]])

In [135]:
c = np.asanyarray(xt).reshape(-1)

In [136]:
c

array([-1.,  0.,  1.,  1., -1.])

In [137]:
np.ndim(c)

1

In [138]:
b = np.asanyarray(yt).reshape(-1)

In [139]:
b

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [140]:
np.ndim(b)

1

In [143]:
a_centered_sp = np.dot(c, b)

In [144]:
a_centered_sp

8.0

In [146]:
N = len(a)

In [147]:
N

5

In [154]:
cov = a_centered_sp/(N-1)

In [155]:
cov

2.0

In [156]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [157]:
at = np.transpose(a)

In [162]:
at

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [164]:
res_cov = np.cov(at)

In [165]:
res_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [168]:
cov2 = res_cov[0, 1]

In [169]:
cov2

2.0

In [170]:
cov == cov2

True